---
config:
  theme: mc
---
erDiagram
Branches{
  String Address
  Int BranchID
  String BranchName
  String City
  String State
  Int Zipcode
}
Employees{
  Int BranchID
  Int EmployeeID
  String FirstName
  Date HiredDate
  String LastName
  Int ManagerID
  String Position
}
Cust_Profile{
  String Address
  Int BatchID
  Int CustomerID
  Date DateOfBirth
  String Email
  String FirstName
  String LastName
  String PhoneNumber
}
Accounts{
  Int AcccountID
  String AccountType
  Float Balance
  Int CreditScore
  String Currency
  Int CustomerID
  Int ManagerID
  Float ODLimit
}
Transactions {
  Int AccountID
  Float Amount
  String Currency
  String Description
  DateTimeStamp EventTS
  String Status
  Boolean  Suspecious
  Date TransactionDate
  Float TransactionFee
  Int TransactionID
  String TransactionType
}
Payments{
  Float Amount
  String AuditTrial
  String ClearingSystem
  String Currency
  String CustomerSegment
  String Description
  Float ExchangeRate
  Float Fee
  Int FromAccountID
  String MerchantName
  Date PaymentDate
  Int PaymentID
  String PaymentType
  Int ToAccountID
}
Loans{
  Float Amount
  String Collateral
  Int CustomerID
  Date EndDate
  Float InterestRate
  Int LoanID
  String LoanType
  String PaymentFrequency
  Date StartDate
  Status String
}
CreditCard{
  Float Balance
  String BillCycle
  Int CardID
  Int CardNumber
  String CardType
  Float CreditLimit
  Int CustomerID
  Date ExpirationDate
  Float InterestRate
  Date IssueDate
  String Status
}
%%Relationships
Branches ||--|{ Employees : "One Branch has one or more Employees"
Branches ||--|{ Cust_Profile  : "One Branch has one more Customers"
Customer||--|{ Accounts : "One Customer has one or more Accouunts"
Accounts||--o{ Transactions : "One Account has zero or more Transactions"
Accounts||--o{ Payments : "From Account - One Account has done zero or more payemnts(Sent)"
Accounts||--o{ Payments : "To Account - One Account has done zero or more payemnts(Received)"
Cust_Profile||--o{ Loans : "Customer has zero or many Loans"
Cust_Profile||--o{ CreditCard : "One Customer has zero or many CreditCard"
Employees||--o{ Employees : "One Manager(Manager ID) has zero or many Reportees(EmployeeID)"











