---
config:
  theme: mc
---
flowchart LR
    A["<b> Source System </b> <br> Data From Different Sources File/DBMS/RDBMS <br>"] 
    --SFT the Source Files into Staging Layer from Source as it is
    --> B["<b>Staging Layer</b> <br> Landing Zone for Raw Data <br>Stores Data Exactly as received<br>Enables Auditing and Reporcessing<br>Minimal Transformation <br>"]
    --Loading Raw Data into Table in DSA Layer
    --> C["<b>DSA Layer</b> <br> Landing Zone for Raw Data <br>Stores Data Exactly as received<br>Enables Auditing and Reporcessing<br>Minimal Transformation <br>"]
    --Cleansing & Scrubing the Data and loading into ODS Layer
    --> D["<b> ODS Layer </b> <br> Cleaned & Standarized Data <br> Remove Duplicates & Fixes Format <br> Standardizes Units & Codes <br> Integrates multiple sources <br>"]
    --Apply Business Complex Rules and loading into EDW Layer
    --> E["<b> EDW Layer </b> <br> Central Historical Repository <br> Stores Dimensions & Facts <br> Applied Business Rules & Derived Metrics <br> Single Source of Truth <br>"]
      E--Apply Business Complex Rules and loading into Data Marts Layer for specific Module/Entity--> F["<b> Data Marts </b> <br> Subject-Specific Datasets <br> Aggregations &amp; KPIs for Departments <br> Improves Performance <br> Deparment-Focused Views <br>"]
      --Speicfic Data Ready for Reorting and Visualization
    --> G["<b> Reporting Layer </b> <br> Presentaion-Ready Data <br> Pre-Aggregated &amp; Formatteed <br> Supports Dashboards &amp; BI Tools <br> Applies Security Filters <br>"]
    E--Common Data Ready for Reorting and Visualization-->G
